language: java
jdk:
  - openjdk12
sudo: false
script: sh scripts/test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 87ba92f2-aaae-4639-904f-0b632e472d33
env:
  global:
    - CODECOV_TOKEN=:87ba92f2-aaae-4639-904f-0b632e472d33