package berlin.yuna.tinkerforgesensor.model.builder;

import berlin.yuna.tinkerforgesensor.model.sensor.brick.DC;
import berlin.yuna.tinkerforgesensor.model.sensor.brick.IMU;
import berlin.yuna.tinkerforgesensor.model.sensor.brick.IMU2;
import berlin.yuna.tinkerforgesensor.model.sensor.brick.Master;
import berlin.yuna.tinkerforgesensor.model.sensor.brick.Servo;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.Accelerometer;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.AccelerometerV2;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.AirQuality;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.Barometer;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.BarometerV2;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.ButtonRGB;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.Default;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.DisplayLcd128x64;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.DisplayLcd20x4;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.DisplaySegment;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.DistanceIR;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.DistanceIRV2;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.DistanceUS;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.DualButton;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.Humidity;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.HumidityV2;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.IO16;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.IO16V2;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.LightAmbient;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.LightAmbientV2;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.LightAmbientV3;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.LightColor;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.LightUv;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.LightUvV2;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.MotionDetector;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.MotionDetectorV2;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.RotaryV2;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.Sensor;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.SoundIntensity;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.SoundPressure;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.Speaker;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.Temperature;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.TemperatureV2;
import berlin.yuna.tinkerforgesensor.model.sensor.bricklet.Tilt;
import java.lang.Class;

/**
 * Autogenerated with [GeneratorCompare:generate]
 */
public class Compare {
    private final Sensor sensor;

    public Compare(final Sensor sensor) {
        this.sensor = sensor;
    }

    public boolean is(final Sensor... sensors) {
        for (Sensor sensor : sensors) {
            if (sensor != null && sensor.uid.equals(this.sensor.uid)) {
                return true;
            }
        }
        return false;
    }

    public boolean is(final Class... sensorOrDevices) {
        for (Class sensorOrDevice : sensorOrDevices) {
            if (sensor.getClass() == sensorOrDevice || sensor.getType() == sensorOrDevice) {
                return true;
            }
        }
        return false;
    }

    public boolean isAccelerometer() {
        return is(AccelerometerV2.class, Accelerometer.class);
    }

    public boolean isAirQuality() {
        return is(AirQuality.class);
    }

    public boolean isBarometer() {
        return is(BarometerV2.class, Barometer.class);
    }

    public boolean isButtonRGB() {
        return is(ButtonRGB.class);
    }

    public boolean isDC() {
        return is(DC.class);
    }

    public boolean isDefault() {
        return is(Default.class);
    }

    public boolean isDisplayLcd128x64() {
        return is(DisplayLcd128x64.class);
    }

    public boolean isDisplayLcd20x4() {
        return is(DisplayLcd20x4.class);
    }

    public boolean isDisplaySegment() {
        return is(DisplaySegment.class);
    }

    public boolean isDistanceIR() {
        return is(DistanceIRV2.class, DistanceIR.class);
    }

    public boolean isDistanceUS() {
        return is(DistanceUS.class);
    }

    public boolean isDualButton() {
        return is(DualButton.class);
    }

    public boolean isHumidity() {
        return is(HumidityV2.class, Humidity.class);
    }

    public boolean isIMU() {
        return is(IMU2.class, IMU.class);
    }

    public boolean isIO16() {
        return is(IO16V2.class, IO16.class);
    }

    public boolean isLightAmbient() {
        return is(LightAmbientV3.class, LightAmbientV2.class, LightAmbient.class);
    }

    public boolean isLightColor() {
        return is(LightColor.class);
    }

    public boolean isLightUv() {
        return is(LightUvV2.class, LightUv.class);
    }

    public boolean isMaster() {
        return is(Master.class);
    }

    public boolean isMotionDetector() {
        return is(MotionDetectorV2.class, MotionDetector.class);
    }

    public boolean isRotary() {
        return is(RotaryV2.class);
    }

    public boolean isServo() {
        return is(Servo.class);
    }

    public boolean isSoundIntensity() {
        return is(SoundIntensity.class);
    }

    public boolean isSoundPressure() {
        return is(SoundPressure.class);
    }

    public boolean isSpeaker() {
        return is(Speaker.class);
    }

    public boolean isTemperature() {
        return is(TemperatureV2.class, Temperature.class);
    }

    public boolean isTilt() {
        return is(Tilt.class);
    }
}
