package berlin.yuna.tinkerforgesensor.model.builder;

import berlin.yuna.tinkerforgesensor.model.sensor.Sensor;
import berlin.yuna.tinkerforgesensor.model.type.ValueType;
import java.lang.Long;
import java.lang.Number;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.LongSummaryStatistics;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.stream.Collectors;

/**
 * Autogenerated with [GeneratorValues:generate]
 */
public class Values extends CopyOnWriteArrayList<Sensor> {
    public Values() {
    }

    public Values(final Collection<? extends Sensor> collection) {
        super(collection);
    }

    public Values(final Sensor[] toCopyIn) {
        super(toCopyIn);
    }

    public Long get(final ValueType valueType, final Long fallBack, final Number valueIndex) {
        final HashMap<Sensor, Long> result = getMap(valueType, -1, valueIndex);
        return result.isEmpty() ? fallBack : result.values().iterator().next();
    }

    public List<Long> getList(final ValueType valueType, final Number timeIndex) {
        final HashMap<Sensor, List<Long>> result = getMap(valueType, timeIndex);
        return result.isEmpty() ? new ArrayList<>() : result.values().iterator().next();
    }

    public LongSummaryStatistics getStatistics(final ValueType valueType, final Number valueIndex) {
        final HashMap<Sensor, LongSummaryStatistics> result = getMapStatistics(valueType, valueIndex);
        return result.isEmpty() ? new LongSummaryStatistics() : result.values().iterator().next();
    }

    public HashMap<Sensor, Long> getMap(final ValueType valueType, final Number timeIndex,
            final Number valueIndex) {
        final HashMap<Sensor, Long> result = new HashMap<>();
        for (Sensor sensor : this) {
            final Number value = sensor.getValue(valueType, timeIndex.intValue(), valueIndex.intValue());
            if (value != null ) {
                result.put(sensor, value.longValue());
            }
        }
        return result;
    }

    public HashMap<Sensor, List<Long>> getMap(final ValueType valueType, final Number timeIndex) {
        final HashMap<Sensor, List<Long>> result = new HashMap<>();
        for (Sensor sensor : this) {
            final List<Number> values = sensor.getValueList(valueType, timeIndex.intValue());
            if (!values.isEmpty()) {
                result.put(sensor, values.stream().map(Number::longValue).collect(Collectors.toList()));
            }
        }
        return result;
    }

    public HashMap<Sensor, LongSummaryStatistics> getMapStatistics(final ValueType valueType,
            final Number valueIndex) {
        final HashMap<Sensor, LongSummaryStatistics> result = new HashMap<>();
        for (Sensor sensor : this) {
            final List<Number> sensorValues = sensor.getValueListVertical(valueType, valueIndex.intValue());
            if (!sensorValues.isEmpty()) {
                result.put(sensor, sensorValues.stream().mapToLong(Number::longValue).summaryStatistics());
            }
        }
        return result;
    }

    public Long all() {
        return all(-1);
    }

    public Long all(final Number valueIndex) {
        return get(ValueType.ALL, -1L, valueIndex);
    }

    public List<Long> all_List() {
        return all_List(-1);
    }

    public List<Long> all_List(final Number timeIndex) {
        return getList(ValueType.ALL, timeIndex);
    }

    public LongSummaryStatistics all_Statistics() {
        return all_Statistics(-1);
    }

    public LongSummaryStatistics all_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.ALL, valueIndex);
    }

    public Long dummy() {
        return dummy(-1);
    }

    public Long dummy(final Number valueIndex) {
        return get(ValueType.DUMMY, -1L, valueIndex);
    }

    public List<Long> dummy_List() {
        return dummy_List(-1);
    }

    public List<Long> dummy_List(final Number timeIndex) {
        return getList(ValueType.DUMMY, timeIndex);
    }

    public LongSummaryStatistics dummy_Statistics() {
        return dummy_Statistics(-1);
    }

    public LongSummaryStatistics dummy_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.DUMMY, valueIndex);
    }

    public Long ping() {
        return ping(-1);
    }

    public Long ping(final Number valueIndex) {
        return get(ValueType.PING, -1L, valueIndex);
    }

    public List<Long> ping_List() {
        return ping_List(-1);
    }

    public List<Long> ping_List(final Number timeIndex) {
        return getList(ValueType.PING, timeIndex);
    }

    public LongSummaryStatistics ping_Statistics() {
        return ping_Statistics(-1);
    }

    public LongSummaryStatistics ping_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.PING, valueIndex);
    }

    public Long deviceStatus() {
        return deviceStatus(-1);
    }

    public Long deviceStatus(final Number valueIndex) {
        return get(ValueType.DEVICE_STATUS, -1L, valueIndex);
    }

    public List<Long> deviceStatus_List() {
        return deviceStatus_List(-1);
    }

    public List<Long> deviceStatus_List(final Number timeIndex) {
        return getList(ValueType.DEVICE_STATUS, timeIndex);
    }

    public LongSummaryStatistics deviceStatus_Statistics() {
        return deviceStatus_Statistics(-1);
    }

    public LongSummaryStatistics deviceStatus_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.DEVICE_STATUS, valueIndex);
    }

    public Long deviceConnected() {
        return deviceConnected(-1);
    }

    public Long deviceConnected(final Number valueIndex) {
        return get(ValueType.DEVICE_CONNECTED, -1L, valueIndex);
    }

    public List<Long> deviceConnected_List() {
        return deviceConnected_List(-1);
    }

    public List<Long> deviceConnected_List(final Number timeIndex) {
        return getList(ValueType.DEVICE_CONNECTED, timeIndex);
    }

    public LongSummaryStatistics deviceConnected_Statistics() {
        return deviceConnected_Statistics(-1);
    }

    public LongSummaryStatistics deviceConnected_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.DEVICE_CONNECTED, valueIndex);
    }

    public Long deviceReconnected() {
        return deviceReconnected(-1);
    }

    public Long deviceReconnected(final Number valueIndex) {
        return get(ValueType.DEVICE_RECONNECTED, -1L, valueIndex);
    }

    public List<Long> deviceReconnected_List() {
        return deviceReconnected_List(-1);
    }

    public List<Long> deviceReconnected_List(final Number timeIndex) {
        return getList(ValueType.DEVICE_RECONNECTED, timeIndex);
    }

    public LongSummaryStatistics deviceReconnected_Statistics() {
        return deviceReconnected_Statistics(-1);
    }

    public LongSummaryStatistics deviceReconnected_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.DEVICE_RECONNECTED, valueIndex);
    }

    public Long deviceDisconnected() {
        return deviceDisconnected(-1);
    }

    public Long deviceDisconnected(final Number valueIndex) {
        return get(ValueType.DEVICE_DISCONNECTED, -1L, valueIndex);
    }

    public List<Long> deviceDisconnected_List() {
        return deviceDisconnected_List(-1);
    }

    public List<Long> deviceDisconnected_List(final Number timeIndex) {
        return getList(ValueType.DEVICE_DISCONNECTED, timeIndex);
    }

    public LongSummaryStatistics deviceDisconnected_Statistics() {
        return deviceDisconnected_Statistics(-1);
    }

    public LongSummaryStatistics deviceDisconnected_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.DEVICE_DISCONNECTED, valueIndex);
    }

    public Long deviceTimeout() {
        return deviceTimeout(-1);
    }

    public Long deviceTimeout(final Number valueIndex) {
        return get(ValueType.DEVICE_TIMEOUT, -1L, valueIndex);
    }

    public List<Long> deviceTimeout_List() {
        return deviceTimeout_List(-1);
    }

    public List<Long> deviceTimeout_List(final Number timeIndex) {
        return getList(ValueType.DEVICE_TIMEOUT, timeIndex);
    }

    public LongSummaryStatistics deviceTimeout_Statistics() {
        return deviceTimeout_Statistics(-1);
    }

    public LongSummaryStatistics deviceTimeout_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.DEVICE_TIMEOUT, valueIndex);
    }

    public Long deviceUnknown() {
        return deviceUnknown(-1);
    }

    public Long deviceUnknown(final Number valueIndex) {
        return get(ValueType.DEVICE_UNKNOWN, -1L, valueIndex);
    }

    public List<Long> deviceUnknown_List() {
        return deviceUnknown_List(-1);
    }

    public List<Long> deviceUnknown_List(final Number timeIndex) {
        return getList(ValueType.DEVICE_UNKNOWN, timeIndex);
    }

    public LongSummaryStatistics deviceUnknown_Statistics() {
        return deviceUnknown_Statistics(-1);
    }

    public LongSummaryStatistics deviceUnknown_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.DEVICE_UNKNOWN, valueIndex);
    }

    public Long emergencyShutdown() {
        return emergencyShutdown(-1);
    }

    public Long emergencyShutdown(final Number valueIndex) {
        return get(ValueType.EMERGENCY_SHUTDOWN, -1L, valueIndex);
    }

    public List<Long> emergencyShutdown_List() {
        return emergencyShutdown_List(-1);
    }

    public List<Long> emergencyShutdown_List(final Number timeIndex) {
        return getList(ValueType.EMERGENCY_SHUTDOWN, timeIndex);
    }

    public LongSummaryStatistics emergencyShutdown_Statistics() {
        return emergencyShutdown_Statistics(-1);
    }

    public LongSummaryStatistics emergencyShutdown_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.EMERGENCY_SHUTDOWN, valueIndex);
    }

    public Long deviceSearch() {
        return deviceSearch(-1);
    }

    public Long deviceSearch(final Number valueIndex) {
        return get(ValueType.DEVICE_SEARCH, -1L, valueIndex);
    }

    public List<Long> deviceSearch_List() {
        return deviceSearch_List(-1);
    }

    public List<Long> deviceSearch_List(final Number timeIndex) {
        return getList(ValueType.DEVICE_SEARCH, timeIndex);
    }

    public LongSummaryStatistics deviceSearch_Statistics() {
        return deviceSearch_Statistics(-1);
    }

    public LongSummaryStatistics deviceSearch_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.DEVICE_SEARCH, valueIndex);
    }

    public Long deviceAlreadyConnected() {
        return deviceAlreadyConnected(-1);
    }

    public Long deviceAlreadyConnected(final Number valueIndex) {
        return get(ValueType.DEVICE_ALREADY_CONNECTED, -1L, valueIndex);
    }

    public List<Long> deviceAlreadyConnected_List() {
        return deviceAlreadyConnected_List(-1);
    }

    public List<Long> deviceAlreadyConnected_List(final Number timeIndex) {
        return getList(ValueType.DEVICE_ALREADY_CONNECTED, timeIndex);
    }

    public LongSummaryStatistics deviceAlreadyConnected_Statistics() {
        return deviceAlreadyConnected_Statistics(-1);
    }

    public LongSummaryStatistics deviceAlreadyConnected_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.DEVICE_ALREADY_CONNECTED, valueIndex);
    }

    public Long environment() {
        return environment(-1);
    }

    public Long environment(final Number valueIndex) {
        return get(ValueType.ENVIRONMENT, -1L, valueIndex);
    }

    public List<Long> environment_List() {
        return environment_List(-1);
    }

    public List<Long> environment_List(final Number timeIndex) {
        return getList(ValueType.ENVIRONMENT, timeIndex);
    }

    public LongSummaryStatistics environment_Statistics() {
        return environment_Statistics(-1);
    }

    public LongSummaryStatistics environment_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.ENVIRONMENT, valueIndex);
    }

    public Long airPressure() {
        return airPressure(-1);
    }

    public Long airPressure(final Number valueIndex) {
        return get(ValueType.AIR_PRESSURE, -1L, valueIndex);
    }

    public List<Long> airPressure_List() {
        return airPressure_List(-1);
    }

    public List<Long> airPressure_List(final Number timeIndex) {
        return getList(ValueType.AIR_PRESSURE, timeIndex);
    }

    public LongSummaryStatistics airPressure_Statistics() {
        return airPressure_Statistics(-1);
    }

    public LongSummaryStatistics airPressure_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.AIR_PRESSURE, valueIndex);
    }

    public Long iaqIndex() {
        return iaqIndex(-1);
    }

    public Long iaqIndex(final Number valueIndex) {
        return get(ValueType.IAQ_INDEX, -1L, valueIndex);
    }

    public List<Long> iaqIndex_List() {
        return iaqIndex_List(-1);
    }

    public List<Long> iaqIndex_List(final Number timeIndex) {
        return getList(ValueType.IAQ_INDEX, timeIndex);
    }

    public LongSummaryStatistics iaqIndex_Statistics() {
        return iaqIndex_Statistics(-1);
    }

    public LongSummaryStatistics iaqIndex_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.IAQ_INDEX, valueIndex);
    }

    public Long humidity() {
        return humidity(-1);
    }

    public Long humidity(final Number valueIndex) {
        return get(ValueType.HUMIDITY, -1L, valueIndex);
    }

    public List<Long> humidity_List() {
        return humidity_List(-1);
    }

    public List<Long> humidity_List(final Number timeIndex) {
        return getList(ValueType.HUMIDITY, timeIndex);
    }

    public LongSummaryStatistics humidity_Statistics() {
        return humidity_Statistics(-1);
    }

    public LongSummaryStatistics humidity_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.HUMIDITY, valueIndex);
    }

    public Long temperature() {
        return temperature(-1);
    }

    public Long temperature(final Number valueIndex) {
        return get(ValueType.TEMPERATURE, -1L, valueIndex);
    }

    public List<Long> temperature_List() {
        return temperature_List(-1);
    }

    public List<Long> temperature_List(final Number timeIndex) {
        return getList(ValueType.TEMPERATURE, timeIndex);
    }

    public LongSummaryStatistics temperature_Statistics() {
        return temperature_Statistics(-1);
    }

    public LongSummaryStatistics temperature_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TEMPERATURE, valueIndex);
    }

    public Long altitude() {
        return altitude(-1);
    }

    public Long altitude(final Number valueIndex) {
        return get(ValueType.ALTITUDE, -1L, valueIndex);
    }

    public List<Long> altitude_List() {
        return altitude_List(-1);
    }

    public List<Long> altitude_List(final Number timeIndex) {
        return getList(ValueType.ALTITUDE, timeIndex);
    }

    public LongSummaryStatistics altitude_Statistics() {
        return altitude_Statistics(-1);
    }

    public LongSummaryStatistics altitude_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.ALTITUDE, valueIndex);
    }

    public Long tilt() {
        return tilt(-1);
    }

    public Long tilt(final Number valueIndex) {
        return get(ValueType.TILT, -1L, valueIndex);
    }

    public List<Long> tilt_List() {
        return tilt_List(-1);
    }

    public List<Long> tilt_List(final Number timeIndex) {
        return getList(ValueType.TILT, timeIndex);
    }

    public LongSummaryStatistics tilt_Statistics() {
        return tilt_Statistics(-1);
    }

    public LongSummaryStatistics tilt_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TILT, valueIndex);
    }

    public Long motionDetected() {
        return motionDetected(-1);
    }

    public Long motionDetected(final Number valueIndex) {
        return get(ValueType.MOTION_DETECTED, -1L, valueIndex);
    }

    public List<Long> motionDetected_List() {
        return motionDetected_List(-1);
    }

    public List<Long> motionDetected_List(final Number timeIndex) {
        return getList(ValueType.MOTION_DETECTED, timeIndex);
    }

    public LongSummaryStatistics motionDetected_Statistics() {
        return motionDetected_Statistics(-1);
    }

    public LongSummaryStatistics motionDetected_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MOTION_DETECTED, valueIndex);
    }

    public Long distance() {
        return distance(-1);
    }

    public Long distance(final Number valueIndex) {
        return get(ValueType.DISTANCE, -1L, valueIndex);
    }

    public List<Long> distance_List() {
        return distance_List(-1);
    }

    public List<Long> distance_List(final Number timeIndex) {
        return getList(ValueType.DISTANCE, timeIndex);
    }

    public LongSummaryStatistics distance_Statistics() {
        return distance_Statistics(-1);
    }

    public LongSummaryStatistics distance_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.DISTANCE, valueIndex);
    }

    public Long sound() {
        return sound(-1);
    }

    public Long sound(final Number valueIndex) {
        return get(ValueType.SOUND, -1L, valueIndex);
    }

    public List<Long> sound_List() {
        return sound_List(-1);
    }

    public List<Long> sound_List(final Number timeIndex) {
        return getList(ValueType.SOUND, timeIndex);
    }

    public LongSummaryStatistics sound_Statistics() {
        return sound_Statistics(-1);
    }

    public LongSummaryStatistics sound_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.SOUND, valueIndex);
    }

    public Long soundSpectrum() {
        return soundSpectrum(-1);
    }

    public Long soundSpectrum(final Number valueIndex) {
        return get(ValueType.SOUND_SPECTRUM, -1L, valueIndex);
    }

    public List<Long> soundSpectrum_List() {
        return soundSpectrum_List(-1);
    }

    public List<Long> soundSpectrum_List(final Number timeIndex) {
        return getList(ValueType.SOUND_SPECTRUM, timeIndex);
    }

    public LongSummaryStatistics soundSpectrum_Statistics() {
        return soundSpectrum_Statistics(-1);
    }

    public LongSummaryStatistics soundSpectrum_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.SOUND_SPECTRUM, valueIndex);
    }

    public Long beepActive() {
        return beepActive(-1);
    }

    public Long beepActive(final Number valueIndex) {
        return get(ValueType.BEEP_ACTIVE, -1L, valueIndex);
    }

    public List<Long> beepActive_List() {
        return beepActive_List(-1);
    }

    public List<Long> beepActive_List(final Number timeIndex) {
        return getList(ValueType.BEEP_ACTIVE, timeIndex);
    }

    public LongSummaryStatistics beepActive_Statistics() {
        return beepActive_Statistics(-1);
    }

    public LongSummaryStatistics beepActive_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.BEEP_ACTIVE, valueIndex);
    }

    public Long soundIntensity() {
        return soundIntensity(-1);
    }

    public Long soundIntensity(final Number valueIndex) {
        return get(ValueType.SOUND_INTENSITY, -1L, valueIndex);
    }

    public List<Long> soundIntensity_List() {
        return soundIntensity_List(-1);
    }

    public List<Long> soundIntensity_List(final Number timeIndex) {
        return getList(ValueType.SOUND_INTENSITY, timeIndex);
    }

    public LongSummaryStatistics soundIntensity_Statistics() {
        return soundIntensity_Statistics(-1);
    }

    public LongSummaryStatistics soundIntensity_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.SOUND_INTENSITY, valueIndex);
    }

    public Long soundDecibel() {
        return soundDecibel(-1);
    }

    public Long soundDecibel(final Number valueIndex) {
        return get(ValueType.SOUND_DECIBEL, -1L, valueIndex);
    }

    public List<Long> soundDecibel_List() {
        return soundDecibel_List(-1);
    }

    public List<Long> soundDecibel_List(final Number timeIndex) {
        return getList(ValueType.SOUND_DECIBEL, timeIndex);
    }

    public LongSummaryStatistics soundDecibel_Statistics() {
        return soundDecibel_Statistics(-1);
    }

    public LongSummaryStatistics soundDecibel_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.SOUND_DECIBEL, valueIndex);
    }

    public Long touch() {
        return touch(-1);
    }

    public Long touch(final Number valueIndex) {
        return get(ValueType.TOUCH, -1L, valueIndex);
    }

    public List<Long> touch_List() {
        return touch_List(-1);
    }

    public List<Long> touch_List(final Number timeIndex) {
        return getList(ValueType.TOUCH, timeIndex);
    }

    public LongSummaryStatistics touch_Statistics() {
        return touch_Statistics(-1);
    }

    public LongSummaryStatistics touch_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TOUCH, valueIndex);
    }

    public Long touch1() {
        return touch1(-1);
    }

    public Long touch1(final Number valueIndex) {
        return get(ValueType.TOUCH_1, -1L, valueIndex);
    }

    public List<Long> touch1_List() {
        return touch1_List(-1);
    }

    public List<Long> touch1_List(final Number timeIndex) {
        return getList(ValueType.TOUCH_1, timeIndex);
    }

    public LongSummaryStatistics touch1_Statistics() {
        return touch1_Statistics(-1);
    }

    public LongSummaryStatistics touch1_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TOUCH_1, valueIndex);
    }

    public Long touch2() {
        return touch2(-1);
    }

    public Long touch2(final Number valueIndex) {
        return get(ValueType.TOUCH_2, -1L, valueIndex);
    }

    public List<Long> touch2_List() {
        return touch2_List(-1);
    }

    public List<Long> touch2_List(final Number timeIndex) {
        return getList(ValueType.TOUCH_2, timeIndex);
    }

    public LongSummaryStatistics touch2_Statistics() {
        return touch2_Statistics(-1);
    }

    public LongSummaryStatistics touch2_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TOUCH_2, valueIndex);
    }

    public Long touch3() {
        return touch3(-1);
    }

    public Long touch3(final Number valueIndex) {
        return get(ValueType.TOUCH_3, -1L, valueIndex);
    }

    public List<Long> touch3_List() {
        return touch3_List(-1);
    }

    public List<Long> touch3_List(final Number timeIndex) {
        return getList(ValueType.TOUCH_3, timeIndex);
    }

    public LongSummaryStatistics touch3_Statistics() {
        return touch3_Statistics(-1);
    }

    public LongSummaryStatistics touch3_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TOUCH_3, valueIndex);
    }

    public Long touch4() {
        return touch4(-1);
    }

    public Long touch4(final Number valueIndex) {
        return get(ValueType.TOUCH_4, -1L, valueIndex);
    }

    public List<Long> touch4_List() {
        return touch4_List(-1);
    }

    public List<Long> touch4_List(final Number timeIndex) {
        return getList(ValueType.TOUCH_4, timeIndex);
    }

    public LongSummaryStatistics touch4_Statistics() {
        return touch4_Statistics(-1);
    }

    public LongSummaryStatistics touch4_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TOUCH_4, valueIndex);
    }

    public Long touch5() {
        return touch5(-1);
    }

    public Long touch5(final Number valueIndex) {
        return get(ValueType.TOUCH_5, -1L, valueIndex);
    }

    public List<Long> touch5_List() {
        return touch5_List(-1);
    }

    public List<Long> touch5_List(final Number timeIndex) {
        return getList(ValueType.TOUCH_5, timeIndex);
    }

    public LongSummaryStatistics touch5_Statistics() {
        return touch5_Statistics(-1);
    }

    public LongSummaryStatistics touch5_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TOUCH_5, valueIndex);
    }

    public Long touch6() {
        return touch6(-1);
    }

    public Long touch6(final Number valueIndex) {
        return get(ValueType.TOUCH_6, -1L, valueIndex);
    }

    public List<Long> touch6_List() {
        return touch6_List(-1);
    }

    public List<Long> touch6_List(final Number timeIndex) {
        return getList(ValueType.TOUCH_6, timeIndex);
    }

    public LongSummaryStatistics touch6_Statistics() {
        return touch6_Statistics(-1);
    }

    public LongSummaryStatistics touch6_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TOUCH_6, valueIndex);
    }

    public Long touch7() {
        return touch7(-1);
    }

    public Long touch7(final Number valueIndex) {
        return get(ValueType.TOUCH_7, -1L, valueIndex);
    }

    public List<Long> touch7_List() {
        return touch7_List(-1);
    }

    public List<Long> touch7_List(final Number timeIndex) {
        return getList(ValueType.TOUCH_7, timeIndex);
    }

    public LongSummaryStatistics touch7_Statistics() {
        return touch7_Statistics(-1);
    }

    public LongSummaryStatistics touch7_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TOUCH_7, valueIndex);
    }

    public Long touch8() {
        return touch8(-1);
    }

    public Long touch8(final Number valueIndex) {
        return get(ValueType.TOUCH_8, -1L, valueIndex);
    }

    public List<Long> touch8_List() {
        return touch8_List(-1);
    }

    public List<Long> touch8_List(final Number timeIndex) {
        return getList(ValueType.TOUCH_8, timeIndex);
    }

    public LongSummaryStatistics touch8_Statistics() {
        return touch8_Statistics(-1);
    }

    public LongSummaryStatistics touch8_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TOUCH_8, valueIndex);
    }

    public Long touch9() {
        return touch9(-1);
    }

    public Long touch9(final Number valueIndex) {
        return get(ValueType.TOUCH_9, -1L, valueIndex);
    }

    public List<Long> touch9_List() {
        return touch9_List(-1);
    }

    public List<Long> touch9_List(final Number timeIndex) {
        return getList(ValueType.TOUCH_9, timeIndex);
    }

    public LongSummaryStatistics touch9_Statistics() {
        return touch9_Statistics(-1);
    }

    public LongSummaryStatistics touch9_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TOUCH_9, valueIndex);
    }

    public Long touch10() {
        return touch10(-1);
    }

    public Long touch10(final Number valueIndex) {
        return get(ValueType.TOUCH_10, -1L, valueIndex);
    }

    public List<Long> touch10_List() {
        return touch10_List(-1);
    }

    public List<Long> touch10_List(final Number timeIndex) {
        return getList(ValueType.TOUCH_10, timeIndex);
    }

    public LongSummaryStatistics touch10_Statistics() {
        return touch10_Statistics(-1);
    }

    public LongSummaryStatistics touch10_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TOUCH_10, valueIndex);
    }

    public Long touch11() {
        return touch11(-1);
    }

    public Long touch11(final Number valueIndex) {
        return get(ValueType.TOUCH_11, -1L, valueIndex);
    }

    public List<Long> touch11_List() {
        return touch11_List(-1);
    }

    public List<Long> touch11_List(final Number timeIndex) {
        return getList(ValueType.TOUCH_11, timeIndex);
    }

    public LongSummaryStatistics touch11_Statistics() {
        return touch11_Statistics(-1);
    }

    public LongSummaryStatistics touch11_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TOUCH_11, valueIndex);
    }

    public Long touch12() {
        return touch12(-1);
    }

    public Long touch12(final Number valueIndex) {
        return get(ValueType.TOUCH_12, -1L, valueIndex);
    }

    public List<Long> touch12_List() {
        return touch12_List(-1);
    }

    public List<Long> touch12_List(final Number timeIndex) {
        return getList(ValueType.TOUCH_12, timeIndex);
    }

    public LongSummaryStatistics touch12_Statistics() {
        return touch12_Statistics(-1);
    }

    public LongSummaryStatistics touch12_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TOUCH_12, valueIndex);
    }

    public Long touchProximity() {
        return touchProximity(-1);
    }

    public Long touchProximity(final Number valueIndex) {
        return get(ValueType.TOUCH_PROXIMITY, -1L, valueIndex);
    }

    public List<Long> touchProximity_List() {
        return touchProximity_List(-1);
    }

    public List<Long> touchProximity_List(final Number timeIndex) {
        return getList(ValueType.TOUCH_PROXIMITY, timeIndex);
    }

    public LongSummaryStatistics touchProximity_Statistics() {
        return touchProximity_Statistics(-1);
    }

    public LongSummaryStatistics touchProximity_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.TOUCH_PROXIMITY, valueIndex);
    }

    public Long light() {
        return light(-1);
    }

    public Long light(final Number valueIndex) {
        return get(ValueType.LIGHT, -1L, valueIndex);
    }

    public List<Long> light_List() {
        return light_List(-1);
    }

    public List<Long> light_List(final Number timeIndex) {
        return getList(ValueType.LIGHT, timeIndex);
    }

    public LongSummaryStatistics light_Statistics() {
        return light_Statistics(-1);
    }

    public LongSummaryStatistics light_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.LIGHT, valueIndex);
    }

    public Long lightUv() {
        return lightUv(-1);
    }

    public Long lightUv(final Number valueIndex) {
        return get(ValueType.LIGHT_UV, -1L, valueIndex);
    }

    public List<Long> lightUv_List() {
        return lightUv_List(-1);
    }

    public List<Long> lightUv_List(final Number timeIndex) {
        return getList(ValueType.LIGHT_UV, timeIndex);
    }

    public LongSummaryStatistics lightUv_Statistics() {
        return lightUv_Statistics(-1);
    }

    public LongSummaryStatistics lightUv_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.LIGHT_UV, valueIndex);
    }

    public Long lightUva() {
        return lightUva(-1);
    }

    public Long lightUva(final Number valueIndex) {
        return get(ValueType.LIGHT_UVA, -1L, valueIndex);
    }

    public List<Long> lightUva_List() {
        return lightUva_List(-1);
    }

    public List<Long> lightUva_List(final Number timeIndex) {
        return getList(ValueType.LIGHT_UVA, timeIndex);
    }

    public LongSummaryStatistics lightUva_Statistics() {
        return lightUva_Statistics(-1);
    }

    public LongSummaryStatistics lightUva_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.LIGHT_UVA, valueIndex);
    }

    public Long lightUvb() {
        return lightUvb(-1);
    }

    public Long lightUvb(final Number valueIndex) {
        return get(ValueType.LIGHT_UVB, -1L, valueIndex);
    }

    public List<Long> lightUvb_List() {
        return lightUvb_List(-1);
    }

    public List<Long> lightUvb_List(final Number timeIndex) {
        return getList(ValueType.LIGHT_UVB, timeIndex);
    }

    public LongSummaryStatistics lightUvb_Statistics() {
        return lightUvb_Statistics(-1);
    }

    public LongSummaryStatistics lightUvb_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.LIGHT_UVB, valueIndex);
    }

    public Long lightLux() {
        return lightLux(-1);
    }

    public Long lightLux(final Number valueIndex) {
        return get(ValueType.LIGHT_LUX, -1L, valueIndex);
    }

    public List<Long> lightLux_List() {
        return lightLux_List(-1);
    }

    public List<Long> lightLux_List(final Number timeIndex) {
        return getList(ValueType.LIGHT_LUX, timeIndex);
    }

    public LongSummaryStatistics lightLux_Statistics() {
        return lightLux_Statistics(-1);
    }

    public LongSummaryStatistics lightLux_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.LIGHT_LUX, valueIndex);
    }

    public Long color() {
        return color(-1);
    }

    public Long color(final Number valueIndex) {
        return get(ValueType.COLOR, -1L, valueIndex);
    }

    public List<Long> color_List() {
        return color_List(-1);
    }

    public List<Long> color_List(final Number timeIndex) {
        return getList(ValueType.COLOR, timeIndex);
    }

    public LongSummaryStatistics color_Statistics() {
        return color_Statistics(-1);
    }

    public LongSummaryStatistics color_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.COLOR, valueIndex);
    }

    public Long colorR() {
        return colorR(-1);
    }

    public Long colorR(final Number valueIndex) {
        return get(ValueType.COLOR_R, -1L, valueIndex);
    }

    public List<Long> colorR_List() {
        return colorR_List(-1);
    }

    public List<Long> colorR_List(final Number timeIndex) {
        return getList(ValueType.COLOR_R, timeIndex);
    }

    public LongSummaryStatistics colorR_Statistics() {
        return colorR_Statistics(-1);
    }

    public LongSummaryStatistics colorR_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.COLOR_R, valueIndex);
    }

    public Long colorG() {
        return colorG(-1);
    }

    public Long colorG(final Number valueIndex) {
        return get(ValueType.COLOR_G, -1L, valueIndex);
    }

    public List<Long> colorG_List() {
        return colorG_List(-1);
    }

    public List<Long> colorG_List(final Number timeIndex) {
        return getList(ValueType.COLOR_G, timeIndex);
    }

    public LongSummaryStatistics colorG_Statistics() {
        return colorG_Statistics(-1);
    }

    public LongSummaryStatistics colorG_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.COLOR_G, valueIndex);
    }

    public Long colorB() {
        return colorB(-1);
    }

    public Long colorB(final Number valueIndex) {
        return get(ValueType.COLOR_B, -1L, valueIndex);
    }

    public List<Long> colorB_List() {
        return colorB_List(-1);
    }

    public List<Long> colorB_List(final Number timeIndex) {
        return getList(ValueType.COLOR_B, timeIndex);
    }

    public LongSummaryStatistics colorB_Statistics() {
        return colorB_Statistics(-1);
    }

    public LongSummaryStatistics colorB_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.COLOR_B, valueIndex);
    }

    public Long colorC() {
        return colorC(-1);
    }

    public Long colorC(final Number valueIndex) {
        return get(ValueType.COLOR_C, -1L, valueIndex);
    }

    public List<Long> colorC_List() {
        return colorC_List(-1);
    }

    public List<Long> colorC_List(final Number timeIndex) {
        return getList(ValueType.COLOR_C, timeIndex);
    }

    public LongSummaryStatistics colorC_Statistics() {
        return colorC_Statistics(-1);
    }

    public LongSummaryStatistics colorC_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.COLOR_C, valueIndex);
    }

    public Long colorRgb() {
        return colorRgb(-1);
    }

    public Long colorRgb(final Number valueIndex) {
        return get(ValueType.COLOR_RGB, -1L, valueIndex);
    }

    public List<Long> colorRgb_List() {
        return colorRgb_List(-1);
    }

    public List<Long> colorRgb_List(final Number timeIndex) {
        return getList(ValueType.COLOR_RGB, timeIndex);
    }

    public LongSummaryStatistics colorRgb_Statistics() {
        return colorRgb_Statistics(-1);
    }

    public LongSummaryStatistics colorRgb_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.COLOR_RGB, valueIndex);
    }

    public Long colorLux() {
        return colorLux(-1);
    }

    public Long colorLux(final Number valueIndex) {
        return get(ValueType.COLOR_LUX, -1L, valueIndex);
    }

    public List<Long> colorLux_List() {
        return colorLux_List(-1);
    }

    public List<Long> colorLux_List(final Number timeIndex) {
        return getList(ValueType.COLOR_LUX, timeIndex);
    }

    public LongSummaryStatistics colorLux_Statistics() {
        return colorLux_Statistics(-1);
    }

    public LongSummaryStatistics colorLux_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.COLOR_LUX, valueIndex);
    }

    public Long colorTemperature() {
        return colorTemperature(-1);
    }

    public Long colorTemperature(final Number valueIndex) {
        return get(ValueType.COLOR_TEMPERATURE, -1L, valueIndex);
    }

    public List<Long> colorTemperature_List() {
        return colorTemperature_List(-1);
    }

    public List<Long> colorTemperature_List(final Number timeIndex) {
        return getList(ValueType.COLOR_TEMPERATURE, timeIndex);
    }

    public LongSummaryStatistics colorTemperature_Statistics() {
        return colorTemperature_Statistics(-1);
    }

    public LongSummaryStatistics colorTemperature_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.COLOR_TEMPERATURE, valueIndex);
    }

    public Long imu() {
        return imu(-1);
    }

    public Long imu(final Number valueIndex) {
        return get(ValueType.IMU, -1L, valueIndex);
    }

    public List<Long> imu_List() {
        return imu_List(-1);
    }

    public List<Long> imu_List(final Number timeIndex) {
        return getList(ValueType.IMU, timeIndex);
    }

    public LongSummaryStatistics imu_Statistics() {
        return imu_Statistics(-1);
    }

    public LongSummaryStatistics imu_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.IMU, valueIndex);
    }

    public Long calibration() {
        return calibration(-1);
    }

    public Long calibration(final Number valueIndex) {
        return get(ValueType.CALIBRATION, -1L, valueIndex);
    }

    public List<Long> calibration_List() {
        return calibration_List(-1);
    }

    public List<Long> calibration_List(final Number timeIndex) {
        return getList(ValueType.CALIBRATION, timeIndex);
    }

    public LongSummaryStatistics calibration_Statistics() {
        return calibration_Statistics(-1);
    }

    public LongSummaryStatistics calibration_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.CALIBRATION, valueIndex);
    }

    public Long orientationHeading() {
        return orientationHeading(-1);
    }

    public Long orientationHeading(final Number valueIndex) {
        return get(ValueType.ORIENTATION_HEADING, -1L, valueIndex);
    }

    public List<Long> orientationHeading_List() {
        return orientationHeading_List(-1);
    }

    public List<Long> orientationHeading_List(final Number timeIndex) {
        return getList(ValueType.ORIENTATION_HEADING, timeIndex);
    }

    public LongSummaryStatistics orientationHeading_Statistics() {
        return orientationHeading_Statistics(-1);
    }

    public LongSummaryStatistics orientationHeading_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.ORIENTATION_HEADING, valueIndex);
    }

    public Long orientationRoll() {
        return orientationRoll(-1);
    }

    public Long orientationRoll(final Number valueIndex) {
        return get(ValueType.ORIENTATION_ROLL, -1L, valueIndex);
    }

    public List<Long> orientationRoll_List() {
        return orientationRoll_List(-1);
    }

    public List<Long> orientationRoll_List(final Number timeIndex) {
        return getList(ValueType.ORIENTATION_ROLL, timeIndex);
    }

    public LongSummaryStatistics orientationRoll_Statistics() {
        return orientationRoll_Statistics(-1);
    }

    public LongSummaryStatistics orientationRoll_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.ORIENTATION_ROLL, valueIndex);
    }

    public Long orientationPitch() {
        return orientationPitch(-1);
    }

    public Long orientationPitch(final Number valueIndex) {
        return get(ValueType.ORIENTATION_PITCH, -1L, valueIndex);
    }

    public List<Long> orientationPitch_List() {
        return orientationPitch_List(-1);
    }

    public List<Long> orientationPitch_List(final Number timeIndex) {
        return getList(ValueType.ORIENTATION_PITCH, timeIndex);
    }

    public LongSummaryStatistics orientationPitch_Statistics() {
        return orientationPitch_Statistics(-1);
    }

    public LongSummaryStatistics orientationPitch_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.ORIENTATION_PITCH, valueIndex);
    }

    public Long accelerationX() {
        return accelerationX(-1);
    }

    public Long accelerationX(final Number valueIndex) {
        return get(ValueType.ACCELERATION_X, -1L, valueIndex);
    }

    public List<Long> accelerationX_List() {
        return accelerationX_List(-1);
    }

    public List<Long> accelerationX_List(final Number timeIndex) {
        return getList(ValueType.ACCELERATION_X, timeIndex);
    }

    public LongSummaryStatistics accelerationX_Statistics() {
        return accelerationX_Statistics(-1);
    }

    public LongSummaryStatistics accelerationX_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.ACCELERATION_X, valueIndex);
    }

    public Long accelerationY() {
        return accelerationY(-1);
    }

    public Long accelerationY(final Number valueIndex) {
        return get(ValueType.ACCELERATION_Y, -1L, valueIndex);
    }

    public List<Long> accelerationY_List() {
        return accelerationY_List(-1);
    }

    public List<Long> accelerationY_List(final Number timeIndex) {
        return getList(ValueType.ACCELERATION_Y, timeIndex);
    }

    public LongSummaryStatistics accelerationY_Statistics() {
        return accelerationY_Statistics(-1);
    }

    public LongSummaryStatistics accelerationY_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.ACCELERATION_Y, valueIndex);
    }

    public Long accelerationZ() {
        return accelerationZ(-1);
    }

    public Long accelerationZ(final Number valueIndex) {
        return get(ValueType.ACCELERATION_Z, -1L, valueIndex);
    }

    public List<Long> accelerationZ_List() {
        return accelerationZ_List(-1);
    }

    public List<Long> accelerationZ_List(final Number timeIndex) {
        return getList(ValueType.ACCELERATION_Z, timeIndex);
    }

    public LongSummaryStatistics accelerationZ_Statistics() {
        return accelerationZ_Statistics(-1);
    }

    public LongSummaryStatistics accelerationZ_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.ACCELERATION_Z, valueIndex);
    }

    public Long magneticX() {
        return magneticX(-1);
    }

    public Long magneticX(final Number valueIndex) {
        return get(ValueType.MAGNETIC_X, -1L, valueIndex);
    }

    public List<Long> magneticX_List() {
        return magneticX_List(-1);
    }

    public List<Long> magneticX_List(final Number timeIndex) {
        return getList(ValueType.MAGNETIC_X, timeIndex);
    }

    public LongSummaryStatistics magneticX_Statistics() {
        return magneticX_Statistics(-1);
    }

    public LongSummaryStatistics magneticX_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MAGNETIC_X, valueIndex);
    }

    public Long magneticY() {
        return magneticY(-1);
    }

    public Long magneticY(final Number valueIndex) {
        return get(ValueType.MAGNETIC_Y, -1L, valueIndex);
    }

    public List<Long> magneticY_List() {
        return magneticY_List(-1);
    }

    public List<Long> magneticY_List(final Number timeIndex) {
        return getList(ValueType.MAGNETIC_Y, timeIndex);
    }

    public LongSummaryStatistics magneticY_Statistics() {
        return magneticY_Statistics(-1);
    }

    public LongSummaryStatistics magneticY_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MAGNETIC_Y, valueIndex);
    }

    public Long magneticZ() {
        return magneticZ(-1);
    }

    public Long magneticZ(final Number valueIndex) {
        return get(ValueType.MAGNETIC_Z, -1L, valueIndex);
    }

    public List<Long> magneticZ_List() {
        return magneticZ_List(-1);
    }

    public List<Long> magneticZ_List(final Number timeIndex) {
        return getList(ValueType.MAGNETIC_Z, timeIndex);
    }

    public LongSummaryStatistics magneticZ_Statistics() {
        return magneticZ_Statistics(-1);
    }

    public LongSummaryStatistics magneticZ_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MAGNETIC_Z, valueIndex);
    }

    public Long angularVelocityX() {
        return angularVelocityX(-1);
    }

    public Long angularVelocityX(final Number valueIndex) {
        return get(ValueType.ANGULAR_VELOCITY_X, -1L, valueIndex);
    }

    public List<Long> angularVelocityX_List() {
        return angularVelocityX_List(-1);
    }

    public List<Long> angularVelocityX_List(final Number timeIndex) {
        return getList(ValueType.ANGULAR_VELOCITY_X, timeIndex);
    }

    public LongSummaryStatistics angularVelocityX_Statistics() {
        return angularVelocityX_Statistics(-1);
    }

    public LongSummaryStatistics angularVelocityX_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.ANGULAR_VELOCITY_X, valueIndex);
    }

    public Long angularVelocityY() {
        return angularVelocityY(-1);
    }

    public Long angularVelocityY(final Number valueIndex) {
        return get(ValueType.ANGULAR_VELOCITY_Y, -1L, valueIndex);
    }

    public List<Long> angularVelocityY_List() {
        return angularVelocityY_List(-1);
    }

    public List<Long> angularVelocityY_List(final Number timeIndex) {
        return getList(ValueType.ANGULAR_VELOCITY_Y, timeIndex);
    }

    public LongSummaryStatistics angularVelocityY_Statistics() {
        return angularVelocityY_Statistics(-1);
    }

    public LongSummaryStatistics angularVelocityY_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.ANGULAR_VELOCITY_Y, valueIndex);
    }

    public Long angularVelocityZ() {
        return angularVelocityZ(-1);
    }

    public Long angularVelocityZ(final Number valueIndex) {
        return get(ValueType.ANGULAR_VELOCITY_Z, -1L, valueIndex);
    }

    public List<Long> angularVelocityZ_List() {
        return angularVelocityZ_List(-1);
    }

    public List<Long> angularVelocityZ_List(final Number timeIndex) {
        return getList(ValueType.ANGULAR_VELOCITY_Z, timeIndex);
    }

    public LongSummaryStatistics angularVelocityZ_Statistics() {
        return angularVelocityZ_Statistics(-1);
    }

    public LongSummaryStatistics angularVelocityZ_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.ANGULAR_VELOCITY_Z, valueIndex);
    }

    public Long eulerAngleX() {
        return eulerAngleX(-1);
    }

    public Long eulerAngleX(final Number valueIndex) {
        return get(ValueType.EULER_ANGLE_X, -1L, valueIndex);
    }

    public List<Long> eulerAngleX_List() {
        return eulerAngleX_List(-1);
    }

    public List<Long> eulerAngleX_List(final Number timeIndex) {
        return getList(ValueType.EULER_ANGLE_X, timeIndex);
    }

    public LongSummaryStatistics eulerAngleX_Statistics() {
        return eulerAngleX_Statistics(-1);
    }

    public LongSummaryStatistics eulerAngleX_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.EULER_ANGLE_X, valueIndex);
    }

    public Long eulerAngleY() {
        return eulerAngleY(-1);
    }

    public Long eulerAngleY(final Number valueIndex) {
        return get(ValueType.EULER_ANGLE_Y, -1L, valueIndex);
    }

    public List<Long> eulerAngleY_List() {
        return eulerAngleY_List(-1);
    }

    public List<Long> eulerAngleY_List(final Number timeIndex) {
        return getList(ValueType.EULER_ANGLE_Y, timeIndex);
    }

    public LongSummaryStatistics eulerAngleY_Statistics() {
        return eulerAngleY_Statistics(-1);
    }

    public LongSummaryStatistics eulerAngleY_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.EULER_ANGLE_Y, valueIndex);
    }

    public Long eulerAngleZ() {
        return eulerAngleZ(-1);
    }

    public Long eulerAngleZ(final Number valueIndex) {
        return get(ValueType.EULER_ANGLE_Z, -1L, valueIndex);
    }

    public List<Long> eulerAngleZ_List() {
        return eulerAngleZ_List(-1);
    }

    public List<Long> eulerAngleZ_List(final Number timeIndex) {
        return getList(ValueType.EULER_ANGLE_Z, timeIndex);
    }

    public LongSummaryStatistics eulerAngleZ_Statistics() {
        return eulerAngleZ_Statistics(-1);
    }

    public LongSummaryStatistics eulerAngleZ_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.EULER_ANGLE_Z, valueIndex);
    }

    public Long quaternionW() {
        return quaternionW(-1);
    }

    public Long quaternionW(final Number valueIndex) {
        return get(ValueType.QUATERNION_W, -1L, valueIndex);
    }

    public List<Long> quaternionW_List() {
        return quaternionW_List(-1);
    }

    public List<Long> quaternionW_List(final Number timeIndex) {
        return getList(ValueType.QUATERNION_W, timeIndex);
    }

    public LongSummaryStatistics quaternionW_Statistics() {
        return quaternionW_Statistics(-1);
    }

    public LongSummaryStatistics quaternionW_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.QUATERNION_W, valueIndex);
    }

    public Long quaternionX() {
        return quaternionX(-1);
    }

    public Long quaternionX(final Number valueIndex) {
        return get(ValueType.QUATERNION_X, -1L, valueIndex);
    }

    public List<Long> quaternionX_List() {
        return quaternionX_List(-1);
    }

    public List<Long> quaternionX_List(final Number timeIndex) {
        return getList(ValueType.QUATERNION_X, timeIndex);
    }

    public LongSummaryStatistics quaternionX_Statistics() {
        return quaternionX_Statistics(-1);
    }

    public LongSummaryStatistics quaternionX_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.QUATERNION_X, valueIndex);
    }

    public Long quaternionY() {
        return quaternionY(-1);
    }

    public Long quaternionY(final Number valueIndex) {
        return get(ValueType.QUATERNION_Y, -1L, valueIndex);
    }

    public List<Long> quaternionY_List() {
        return quaternionY_List(-1);
    }

    public List<Long> quaternionY_List(final Number timeIndex) {
        return getList(ValueType.QUATERNION_Y, timeIndex);
    }

    public LongSummaryStatistics quaternionY_Statistics() {
        return quaternionY_Statistics(-1);
    }

    public LongSummaryStatistics quaternionY_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.QUATERNION_Y, valueIndex);
    }

    public Long quaternionZ() {
        return quaternionZ(-1);
    }

    public Long quaternionZ(final Number valueIndex) {
        return get(ValueType.QUATERNION_Z, -1L, valueIndex);
    }

    public List<Long> quaternionZ_List() {
        return quaternionZ_List(-1);
    }

    public List<Long> quaternionZ_List(final Number timeIndex) {
        return getList(ValueType.QUATERNION_Z, timeIndex);
    }

    public LongSummaryStatistics quaternionZ_Statistics() {
        return quaternionZ_Statistics(-1);
    }

    public LongSummaryStatistics quaternionZ_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.QUATERNION_Z, valueIndex);
    }

    public Long linearAccelerationX() {
        return linearAccelerationX(-1);
    }

    public Long linearAccelerationX(final Number valueIndex) {
        return get(ValueType.LINEAR_ACCELERATION_X, -1L, valueIndex);
    }

    public List<Long> linearAccelerationX_List() {
        return linearAccelerationX_List(-1);
    }

    public List<Long> linearAccelerationX_List(final Number timeIndex) {
        return getList(ValueType.LINEAR_ACCELERATION_X, timeIndex);
    }

    public LongSummaryStatistics linearAccelerationX_Statistics() {
        return linearAccelerationX_Statistics(-1);
    }

    public LongSummaryStatistics linearAccelerationX_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.LINEAR_ACCELERATION_X, valueIndex);
    }

    public Long linearAccelerationY() {
        return linearAccelerationY(-1);
    }

    public Long linearAccelerationY(final Number valueIndex) {
        return get(ValueType.LINEAR_ACCELERATION_Y, -1L, valueIndex);
    }

    public List<Long> linearAccelerationY_List() {
        return linearAccelerationY_List(-1);
    }

    public List<Long> linearAccelerationY_List(final Number timeIndex) {
        return getList(ValueType.LINEAR_ACCELERATION_Y, timeIndex);
    }

    public LongSummaryStatistics linearAccelerationY_Statistics() {
        return linearAccelerationY_Statistics(-1);
    }

    public LongSummaryStatistics linearAccelerationY_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.LINEAR_ACCELERATION_Y, valueIndex);
    }

    public Long linearAccelerationZ() {
        return linearAccelerationZ(-1);
    }

    public Long linearAccelerationZ(final Number valueIndex) {
        return get(ValueType.LINEAR_ACCELERATION_Z, -1L, valueIndex);
    }

    public List<Long> linearAccelerationZ_List() {
        return linearAccelerationZ_List(-1);
    }

    public List<Long> linearAccelerationZ_List(final Number timeIndex) {
        return getList(ValueType.LINEAR_ACCELERATION_Z, timeIndex);
    }

    public LongSummaryStatistics linearAccelerationZ_Statistics() {
        return linearAccelerationZ_Statistics(-1);
    }

    public LongSummaryStatistics linearAccelerationZ_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.LINEAR_ACCELERATION_Z, valueIndex);
    }

    public Long gravityVectorX() {
        return gravityVectorX(-1);
    }

    public Long gravityVectorX(final Number valueIndex) {
        return get(ValueType.GRAVITY_VECTOR_X, -1L, valueIndex);
    }

    public List<Long> gravityVectorX_List() {
        return gravityVectorX_List(-1);
    }

    public List<Long> gravityVectorX_List(final Number timeIndex) {
        return getList(ValueType.GRAVITY_VECTOR_X, timeIndex);
    }

    public LongSummaryStatistics gravityVectorX_Statistics() {
        return gravityVectorX_Statistics(-1);
    }

    public LongSummaryStatistics gravityVectorX_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.GRAVITY_VECTOR_X, valueIndex);
    }

    public Long gravityVectorY() {
        return gravityVectorY(-1);
    }

    public Long gravityVectorY(final Number valueIndex) {
        return get(ValueType.GRAVITY_VECTOR_Y, -1L, valueIndex);
    }

    public List<Long> gravityVectorY_List() {
        return gravityVectorY_List(-1);
    }

    public List<Long> gravityVectorY_List(final Number timeIndex) {
        return getList(ValueType.GRAVITY_VECTOR_Y, timeIndex);
    }

    public LongSummaryStatistics gravityVectorY_Statistics() {
        return gravityVectorY_Statistics(-1);
    }

    public LongSummaryStatistics gravityVectorY_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.GRAVITY_VECTOR_Y, valueIndex);
    }

    public Long gravityVectorZ() {
        return gravityVectorZ(-1);
    }

    public Long gravityVectorZ(final Number valueIndex) {
        return get(ValueType.GRAVITY_VECTOR_Z, -1L, valueIndex);
    }

    public List<Long> gravityVectorZ_List() {
        return gravityVectorZ_List(-1);
    }

    public List<Long> gravityVectorZ_List(final Number timeIndex) {
        return getList(ValueType.GRAVITY_VECTOR_Z, timeIndex);
    }

    public LongSummaryStatistics gravityVectorZ_Statistics() {
        return gravityVectorZ_Statistics(-1);
    }

    public LongSummaryStatistics gravityVectorZ_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.GRAVITY_VECTOR_Z, valueIndex);
    }

    public Long energy() {
        return energy(-1);
    }

    public Long energy(final Number valueIndex) {
        return get(ValueType.ENERGY, -1L, valueIndex);
    }

    public List<Long> energy_List() {
        return energy_List(-1);
    }

    public List<Long> energy_List(final Number timeIndex) {
        return getList(ValueType.ENERGY, timeIndex);
    }

    public LongSummaryStatistics energy_Statistics() {
        return energy_Statistics(-1);
    }

    public LongSummaryStatistics energy_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.ENERGY, valueIndex);
    }

    public Long power() {
        return power(-1);
    }

    public Long power(final Number valueIndex) {
        return get(ValueType.POWER, -1L, valueIndex);
    }

    public List<Long> power_List() {
        return power_List(-1);
    }

    public List<Long> power_List(final Number timeIndex) {
        return getList(ValueType.POWER, timeIndex);
    }

    public LongSummaryStatistics power_Statistics() {
        return power_Statistics(-1);
    }

    public LongSummaryStatistics power_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.POWER, valueIndex);
    }

    public Long voltageUsb() {
        return voltageUsb(-1);
    }

    public Long voltageUsb(final Number valueIndex) {
        return get(ValueType.VOLTAGE_USB, -1L, valueIndex);
    }

    public List<Long> voltageUsb_List() {
        return voltageUsb_List(-1);
    }

    public List<Long> voltageUsb_List(final Number timeIndex) {
        return getList(ValueType.VOLTAGE_USB, timeIndex);
    }

    public LongSummaryStatistics voltageUsb_Statistics() {
        return voltageUsb_Statistics(-1);
    }

    public LongSummaryStatistics voltageUsb_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.VOLTAGE_USB, valueIndex);
    }

    public Long voltage() {
        return voltage(-1);
    }

    public Long voltage(final Number valueIndex) {
        return get(ValueType.VOLTAGE, -1L, valueIndex);
    }

    public List<Long> voltage_List() {
        return voltage_List(-1);
    }

    public List<Long> voltage_List(final Number timeIndex) {
        return getList(ValueType.VOLTAGE, timeIndex);
    }

    public LongSummaryStatistics voltage_Statistics() {
        return voltage_Statistics(-1);
    }

    public LongSummaryStatistics voltage_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.VOLTAGE, valueIndex);
    }

    public Long underVoltage() {
        return underVoltage(-1);
    }

    public Long underVoltage(final Number valueIndex) {
        return get(ValueType.UNDER_VOLTAGE, -1L, valueIndex);
    }

    public List<Long> underVoltage_List() {
        return underVoltage_List(-1);
    }

    public List<Long> underVoltage_List(final Number timeIndex) {
        return getList(ValueType.UNDER_VOLTAGE, timeIndex);
    }

    public LongSummaryStatistics underVoltage_Statistics() {
        return underVoltage_Statistics(-1);
    }

    public LongSummaryStatistics underVoltage_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.UNDER_VOLTAGE, valueIndex);
    }

    public Long current() {
        return current(-1);
    }

    public Long current(final Number valueIndex) {
        return get(ValueType.CURRENT, -1L, valueIndex);
    }

    public List<Long> current_List() {
        return current_List(-1);
    }

    public List<Long> current_List(final Number timeIndex) {
        return getList(ValueType.CURRENT, timeIndex);
    }

    public LongSummaryStatistics current_Statistics() {
        return current_Statistics(-1);
    }

    public LongSummaryStatistics current_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.CURRENT, valueIndex);
    }

    public Long button() {
        return button(-1);
    }

    public Long button(final Number valueIndex) {
        return get(ValueType.BUTTON, -1L, valueIndex);
    }

    public List<Long> button_List() {
        return button_List(-1);
    }

    public List<Long> button_List(final Number timeIndex) {
        return getList(ValueType.BUTTON, timeIndex);
    }

    public LongSummaryStatistics button_Statistics() {
        return button_Statistics(-1);
    }

    public LongSummaryStatistics button_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.BUTTON, valueIndex);
    }

    public Long buttonPressed() {
        return buttonPressed(-1);
    }

    public Long buttonPressed(final Number valueIndex) {
        return get(ValueType.BUTTON_PRESSED, -1L, valueIndex);
    }

    public List<Long> buttonPressed_List() {
        return buttonPressed_List(-1);
    }

    public List<Long> buttonPressed_List(final Number timeIndex) {
        return getList(ValueType.BUTTON_PRESSED, timeIndex);
    }

    public LongSummaryStatistics buttonPressed_Statistics() {
        return buttonPressed_Statistics(-1);
    }

    public LongSummaryStatistics buttonPressed_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.BUTTON_PRESSED, valueIndex);
    }

    public Long rotary() {
        return rotary(-1);
    }

    public Long rotary(final Number valueIndex) {
        return get(ValueType.ROTARY, -1L, valueIndex);
    }

    public List<Long> rotary_List() {
        return rotary_List(-1);
    }

    public List<Long> rotary_List(final Number timeIndex) {
        return getList(ValueType.ROTARY, timeIndex);
    }

    public LongSummaryStatistics rotary_Statistics() {
        return rotary_Statistics(-1);
    }

    public LongSummaryStatistics rotary_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.ROTARY, valueIndex);
    }

    public Long motor() {
        return motor(-1);
    }

    public Long motor(final Number valueIndex) {
        return get(ValueType.MOTOR, -1L, valueIndex);
    }

    public List<Long> motor_List() {
        return motor_List(-1);
    }

    public List<Long> motor_List(final Number timeIndex) {
        return getList(ValueType.MOTOR, timeIndex);
    }

    public LongSummaryStatistics motor_Statistics() {
        return motor_Statistics(-1);
    }

    public LongSummaryStatistics motor_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MOTOR, valueIndex);
    }

    public Long motorPosition() {
        return motorPosition(-1);
    }

    public Long motorPosition(final Number valueIndex) {
        return get(ValueType.MOTOR_POSITION, -1L, valueIndex);
    }

    public List<Long> motorPosition_List() {
        return motorPosition_List(-1);
    }

    public List<Long> motorPosition_List(final Number timeIndex) {
        return getList(ValueType.MOTOR_POSITION, timeIndex);
    }

    public LongSummaryStatistics motorPosition_Statistics() {
        return motorPosition_Statistics(-1);
    }

    public LongSummaryStatistics motorPosition_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MOTOR_POSITION, valueIndex);
    }

    public Long motorVelocity() {
        return motorVelocity(-1);
    }

    public Long motorVelocity(final Number valueIndex) {
        return get(ValueType.MOTOR_VELOCITY, -1L, valueIndex);
    }

    public List<Long> motorVelocity_List() {
        return motorVelocity_List(-1);
    }

    public List<Long> motorVelocity_List(final Number timeIndex) {
        return getList(ValueType.MOTOR_VELOCITY, timeIndex);
    }

    public LongSummaryStatistics motorVelocity_Statistics() {
        return motorVelocity_Statistics(-1);
    }

    public LongSummaryStatistics motorVelocity_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MOTOR_VELOCITY, valueIndex);
    }

    public Long humanInput() {
        return humanInput(-1);
    }

    public Long humanInput(final Number valueIndex) {
        return get(ValueType.HUMAN_INPUT, -1L, valueIndex);
    }

    public List<Long> humanInput_List() {
        return humanInput_List(-1);
    }

    public List<Long> humanInput_List(final Number timeIndex) {
        return getList(ValueType.HUMAN_INPUT, timeIndex);
    }

    public LongSummaryStatistics humanInput_Statistics() {
        return humanInput_Statistics(-1);
    }

    public LongSummaryStatistics humanInput_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.HUMAN_INPUT, valueIndex);
    }

    public Long keyInput() {
        return keyInput(-1);
    }

    public Long keyInput(final Number valueIndex) {
        return get(ValueType.KEY_INPUT, -1L, valueIndex);
    }

    public List<Long> keyInput_List() {
        return keyInput_List(-1);
    }

    public List<Long> keyInput_List(final Number timeIndex) {
        return getList(ValueType.KEY_INPUT, timeIndex);
    }

    public LongSummaryStatistics keyInput_Statistics() {
        return keyInput_Statistics(-1);
    }

    public LongSummaryStatistics keyInput_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.KEY_INPUT, valueIndex);
    }

    public Long keyPressed() {
        return keyPressed(-1);
    }

    public Long keyPressed(final Number valueIndex) {
        return get(ValueType.KEY_PRESSED, -1L, valueIndex);
    }

    public List<Long> keyPressed_List() {
        return keyPressed_List(-1);
    }

    public List<Long> keyPressed_List(final Number timeIndex) {
        return getList(ValueType.KEY_PRESSED, timeIndex);
    }

    public LongSummaryStatistics keyPressed_Statistics() {
        return keyPressed_Statistics(-1);
    }

    public LongSummaryStatistics keyPressed_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.KEY_PRESSED, valueIndex);
    }

    public Long keyReleased() {
        return keyReleased(-1);
    }

    public Long keyReleased(final Number valueIndex) {
        return get(ValueType.KEY_RELEASED, -1L, valueIndex);
    }

    public List<Long> keyReleased_List() {
        return keyReleased_List(-1);
    }

    public List<Long> keyReleased_List(final Number timeIndex) {
        return getList(ValueType.KEY_RELEASED, timeIndex);
    }

    public LongSummaryStatistics keyReleased_Statistics() {
        return keyReleased_Statistics(-1);
    }

    public LongSummaryStatistics keyReleased_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.KEY_RELEASED, valueIndex);
    }

    public Long keyChar() {
        return keyChar(-1);
    }

    public Long keyChar(final Number valueIndex) {
        return get(ValueType.KEY_CHAR, -1L, valueIndex);
    }

    public List<Long> keyChar_List() {
        return keyChar_List(-1);
    }

    public List<Long> keyChar_List(final Number timeIndex) {
        return getList(ValueType.KEY_CHAR, timeIndex);
    }

    public LongSummaryStatistics keyChar_Statistics() {
        return keyChar_Statistics(-1);
    }

    public LongSummaryStatistics keyChar_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.KEY_CHAR, valueIndex);
    }

    public Long mouseInput() {
        return mouseInput(-1);
    }

    public Long mouseInput(final Number valueIndex) {
        return get(ValueType.MOUSE_INPUT, -1L, valueIndex);
    }

    public List<Long> mouseInput_List() {
        return mouseInput_List(-1);
    }

    public List<Long> mouseInput_List(final Number timeIndex) {
        return getList(ValueType.MOUSE_INPUT, timeIndex);
    }

    public LongSummaryStatistics mouseInput_Statistics() {
        return mouseInput_Statistics(-1);
    }

    public LongSummaryStatistics mouseInput_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MOUSE_INPUT, valueIndex);
    }

    public Long mouseClickCount() {
        return mouseClickCount(-1);
    }

    public Long mouseClickCount(final Number valueIndex) {
        return get(ValueType.MOUSE_CLICK_COUNT, -1L, valueIndex);
    }

    public List<Long> mouseClickCount_List() {
        return mouseClickCount_List(-1);
    }

    public List<Long> mouseClickCount_List(final Number timeIndex) {
        return getList(ValueType.MOUSE_CLICK_COUNT, timeIndex);
    }

    public LongSummaryStatistics mouseClickCount_Statistics() {
        return mouseClickCount_Statistics(-1);
    }

    public LongSummaryStatistics mouseClickCount_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MOUSE_CLICK_COUNT, valueIndex);
    }

    public Long mousePressed() {
        return mousePressed(-1);
    }

    public Long mousePressed(final Number valueIndex) {
        return get(ValueType.MOUSE_PRESSED, -1L, valueIndex);
    }

    public List<Long> mousePressed_List() {
        return mousePressed_List(-1);
    }

    public List<Long> mousePressed_List(final Number timeIndex) {
        return getList(ValueType.MOUSE_PRESSED, timeIndex);
    }

    public LongSummaryStatistics mousePressed_Statistics() {
        return mousePressed_Statistics(-1);
    }

    public LongSummaryStatistics mousePressed_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MOUSE_PRESSED, valueIndex);
    }

    public Long mouseReleased() {
        return mouseReleased(-1);
    }

    public Long mouseReleased(final Number valueIndex) {
        return get(ValueType.MOUSE_RELEASED, -1L, valueIndex);
    }

    public List<Long> mouseReleased_List() {
        return mouseReleased_List(-1);
    }

    public List<Long> mouseReleased_List(final Number timeIndex) {
        return getList(ValueType.MOUSE_RELEASED, timeIndex);
    }

    public LongSummaryStatistics mouseReleased_Statistics() {
        return mouseReleased_Statistics(-1);
    }

    public LongSummaryStatistics mouseReleased_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MOUSE_RELEASED, valueIndex);
    }

    public Long mouseEntered() {
        return mouseEntered(-1);
    }

    public Long mouseEntered(final Number valueIndex) {
        return get(ValueType.MOUSE_ENTERED, -1L, valueIndex);
    }

    public List<Long> mouseEntered_List() {
        return mouseEntered_List(-1);
    }

    public List<Long> mouseEntered_List(final Number timeIndex) {
        return getList(ValueType.MOUSE_ENTERED, timeIndex);
    }

    public LongSummaryStatistics mouseEntered_Statistics() {
        return mouseEntered_Statistics(-1);
    }

    public LongSummaryStatistics mouseEntered_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MOUSE_ENTERED, valueIndex);
    }

    public Long mouseExited() {
        return mouseExited(-1);
    }

    public Long mouseExited(final Number valueIndex) {
        return get(ValueType.MOUSE_EXITED, -1L, valueIndex);
    }

    public List<Long> mouseExited_List() {
        return mouseExited_List(-1);
    }

    public List<Long> mouseExited_List(final Number timeIndex) {
        return getList(ValueType.MOUSE_EXITED, timeIndex);
    }

    public LongSummaryStatistics mouseExited_Statistics() {
        return mouseExited_Statistics(-1);
    }

    public LongSummaryStatistics mouseExited_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MOUSE_EXITED, valueIndex);
    }

    public Long mouseDragged() {
        return mouseDragged(-1);
    }

    public Long mouseDragged(final Number valueIndex) {
        return get(ValueType.MOUSE_DRAGGED, -1L, valueIndex);
    }

    public List<Long> mouseDragged_List() {
        return mouseDragged_List(-1);
    }

    public List<Long> mouseDragged_List(final Number timeIndex) {
        return getList(ValueType.MOUSE_DRAGGED, timeIndex);
    }

    public LongSummaryStatistics mouseDragged_Statistics() {
        return mouseDragged_Statistics(-1);
    }

    public LongSummaryStatistics mouseDragged_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MOUSE_DRAGGED, valueIndex);
    }

    public Long mouseMoved() {
        return mouseMoved(-1);
    }

    public Long mouseMoved(final Number valueIndex) {
        return get(ValueType.MOUSE_MOVED, -1L, valueIndex);
    }

    public List<Long> mouseMoved_List() {
        return mouseMoved_List(-1);
    }

    public List<Long> mouseMoved_List(final Number timeIndex) {
        return getList(ValueType.MOUSE_MOVED, timeIndex);
    }

    public LongSummaryStatistics mouseMoved_Statistics() {
        return mouseMoved_Statistics(-1);
    }

    public LongSummaryStatistics mouseMoved_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MOUSE_MOVED, valueIndex);
    }

    public Long mouseMoveX() {
        return mouseMoveX(-1);
    }

    public Long mouseMoveX(final Number valueIndex) {
        return get(ValueType.MOUSE_MOVE_X, -1L, valueIndex);
    }

    public List<Long> mouseMoveX_List() {
        return mouseMoveX_List(-1);
    }

    public List<Long> mouseMoveX_List(final Number timeIndex) {
        return getList(ValueType.MOUSE_MOVE_X, timeIndex);
    }

    public LongSummaryStatistics mouseMoveX_Statistics() {
        return mouseMoveX_Statistics(-1);
    }

    public LongSummaryStatistics mouseMoveX_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MOUSE_MOVE_X, valueIndex);
    }

    public Long mouseMoveY() {
        return mouseMoveY(-1);
    }

    public Long mouseMoveY(final Number valueIndex) {
        return get(ValueType.MOUSE_MOVE_Y, -1L, valueIndex);
    }

    public List<Long> mouseMoveY_List() {
        return mouseMoveY_List(-1);
    }

    public List<Long> mouseMoveY_List(final Number timeIndex) {
        return getList(ValueType.MOUSE_MOVE_Y, timeIndex);
    }

    public LongSummaryStatistics mouseMoveY_Statistics() {
        return mouseMoveY_Statistics(-1);
    }

    public LongSummaryStatistics mouseMoveY_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MOUSE_MOVE_Y, valueIndex);
    }

    public Long mouseWheelMoved() {
        return mouseWheelMoved(-1);
    }

    public Long mouseWheelMoved(final Number valueIndex) {
        return get(ValueType.MOUSE_WHEEL_MOVED, -1L, valueIndex);
    }

    public List<Long> mouseWheelMoved_List() {
        return mouseWheelMoved_List(-1);
    }

    public List<Long> mouseWheelMoved_List(final Number timeIndex) {
        return getList(ValueType.MOUSE_WHEEL_MOVED, timeIndex);
    }

    public LongSummaryStatistics mouseWheelMoved_Statistics() {
        return mouseWheelMoved_Statistics(-1);
    }

    public LongSummaryStatistics mouseWheelMoved_Statistics(final Number valueIndex) {
        return getStatistics(ValueType.MOUSE_WHEEL_MOVED, valueIndex);
    }
}
