package berlin.yuna.tinkerforgesensor.model;

import berlin.yuna.tinkerforgesensor.model.sensor.Accelerometer;
import berlin.yuna.tinkerforgesensor.model.sensor.AccelerometerV2;
import berlin.yuna.tinkerforgesensor.model.sensor.AirQuality;
import berlin.yuna.tinkerforgesensor.model.sensor.Barometer;
import berlin.yuna.tinkerforgesensor.model.sensor.BarometerV2;
import berlin.yuna.tinkerforgesensor.model.sensor.ButtonRGB;
import berlin.yuna.tinkerforgesensor.model.sensor.DC;
import berlin.yuna.tinkerforgesensor.model.sensor.Default;
import berlin.yuna.tinkerforgesensor.model.sensor.DisplayLcd128x64;
import berlin.yuna.tinkerforgesensor.model.sensor.DisplayLcd20x4;
import berlin.yuna.tinkerforgesensor.model.sensor.DisplaySegment;
import berlin.yuna.tinkerforgesensor.model.sensor.DisplaySegmentV2;
import berlin.yuna.tinkerforgesensor.model.sensor.DistanceIR;
import berlin.yuna.tinkerforgesensor.model.sensor.DistanceIRV2;
import berlin.yuna.tinkerforgesensor.model.sensor.DistanceUS;
import berlin.yuna.tinkerforgesensor.model.sensor.DualButton;
import berlin.yuna.tinkerforgesensor.model.sensor.Humidity;
import berlin.yuna.tinkerforgesensor.model.sensor.HumidityV2;
import berlin.yuna.tinkerforgesensor.model.sensor.IMU;
import berlin.yuna.tinkerforgesensor.model.sensor.IMUV2;
import berlin.yuna.tinkerforgesensor.model.sensor.IO16;
import berlin.yuna.tinkerforgesensor.model.sensor.IO16V2;
import berlin.yuna.tinkerforgesensor.model.sensor.LedRGBV2;
import berlin.yuna.tinkerforgesensor.model.sensor.LightAmbient;
import berlin.yuna.tinkerforgesensor.model.sensor.LightAmbientV2;
import berlin.yuna.tinkerforgesensor.model.sensor.LightAmbientV3;
import berlin.yuna.tinkerforgesensor.model.sensor.LightColor;
import berlin.yuna.tinkerforgesensor.model.sensor.LightUv;
import berlin.yuna.tinkerforgesensor.model.sensor.LightUvV2;
import berlin.yuna.tinkerforgesensor.model.sensor.LocalAudio;
import berlin.yuna.tinkerforgesensor.model.sensor.LocalControl;
import berlin.yuna.tinkerforgesensor.model.sensor.Master;
import berlin.yuna.tinkerforgesensor.model.sensor.MotionDetector;
import berlin.yuna.tinkerforgesensor.model.sensor.MotionDetectorV2;
import berlin.yuna.tinkerforgesensor.model.sensor.RotaryV2;
import berlin.yuna.tinkerforgesensor.model.sensor.Sensor;
import berlin.yuna.tinkerforgesensor.model.sensor.Servo;
import berlin.yuna.tinkerforgesensor.model.sensor.SoundIntensity;
import berlin.yuna.tinkerforgesensor.model.sensor.SoundPressure;
import berlin.yuna.tinkerforgesensor.model.sensor.Speaker;
import berlin.yuna.tinkerforgesensor.model.sensor.Temperature;
import berlin.yuna.tinkerforgesensor.model.sensor.TemperatureV2;
import berlin.yuna.tinkerforgesensor.model.sensor.Tilt;
import com.tinkerforge.BrickDC;
import com.tinkerforge.BrickIMU;
import com.tinkerforge.BrickIMUV2;
import com.tinkerforge.BrickMaster;
import com.tinkerforge.BrickServo;
import com.tinkerforge.BrickletAccelerometer;
import com.tinkerforge.BrickletAccelerometerV2;
import com.tinkerforge.BrickletAirQuality;
import com.tinkerforge.BrickletAmbientLight;
import com.tinkerforge.BrickletAmbientLightV2;
import com.tinkerforge.BrickletAmbientLightV3;
import com.tinkerforge.BrickletBarometer;
import com.tinkerforge.BrickletBarometerV2;
import com.tinkerforge.BrickletColor;
import com.tinkerforge.BrickletDistanceIR;
import com.tinkerforge.BrickletDistanceIRV2;
import com.tinkerforge.BrickletDistanceUS;
import com.tinkerforge.BrickletDualButtonV2;
import com.tinkerforge.BrickletHumidity;
import com.tinkerforge.BrickletHumidityV2;
import com.tinkerforge.BrickletIO16;
import com.tinkerforge.BrickletIO16V2;
import com.tinkerforge.BrickletLCD128x64;
import com.tinkerforge.BrickletLCD20x4;
import com.tinkerforge.BrickletMotionDetector;
import com.tinkerforge.BrickletMotionDetectorV2;
import com.tinkerforge.BrickletPiezoSpeaker;
import com.tinkerforge.BrickletRGBLEDButton;
import com.tinkerforge.BrickletRGBLEDV2;
import com.tinkerforge.BrickletRotaryEncoderV2;
import com.tinkerforge.BrickletSegmentDisplay4x7;
import com.tinkerforge.BrickletSegmentDisplay4x7V2;
import com.tinkerforge.BrickletSoundIntensity;
import com.tinkerforge.BrickletSoundPressureLevel;
import com.tinkerforge.BrickletTemperature;
import com.tinkerforge.BrickletTemperatureV2;
import com.tinkerforge.BrickletTilt;
import com.tinkerforge.BrickletUVLight;
import com.tinkerforge.BrickletUVLightV2;
import com.tinkerforge.Device;
import com.tinkerforge.DummyDevice;
import java.lang.Class;
import java.lang.Integer;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

/**
 * <h3>{@link SensorRegistry}</h3>
 * <i>contains mapping of {@link Device} and {@link Sensor}</i><br/>
 * <i>Autogenerated with [GeneratorSensorRegistry:generate]
 * <hr><ul>
 * <li>Device {@link BrickletAccelerometer} => Sensor {@link Accelerometer}</li>
 * <li>Device {@link BrickletAccelerometerV2} => Sensor {@link AccelerometerV2}</li>
 * <li>Device {@link BrickletAirQuality} => Sensor {@link AirQuality}</li>
 * <li>Device {@link BrickletBarometer} => Sensor {@link Barometer}</li>
 * <li>Device {@link BrickletBarometerV2} => Sensor {@link BarometerV2}</li>
 * <li>Device {@link BrickletRGBLEDButton} => Sensor {@link ButtonRGB}</li>
 * <li>Device {@link BrickDC} => Sensor {@link DC}</li>
 * <li>Device {@link DummyDevice} => Sensor {@link Default}</li>
 * <li>Device {@link BrickletLCD128x64} => Sensor {@link DisplayLcd128x64}</li>
 * <li>Device {@link BrickletLCD20x4} => Sensor {@link DisplayLcd20x4}</li>
 * <li>Device {@link BrickletSegmentDisplay4x7} => Sensor {@link DisplaySegment}</li>
 * <li>Device {@link BrickletSegmentDisplay4x7V2} => Sensor {@link DisplaySegmentV2}</li>
 * <li>Device {@link BrickletDistanceIR} => Sensor {@link DistanceIR}</li>
 * <li>Device {@link BrickletDistanceIRV2} => Sensor {@link DistanceIRV2}</li>
 * <li>Device {@link BrickletDistanceUS} => Sensor {@link DistanceUS}</li>
 * <li>Device {@link BrickletDualButtonV2} => Sensor {@link DualButton}</li>
 * <li>Device {@link BrickletHumidity} => Sensor {@link Humidity}</li>
 * <li>Device {@link BrickletHumidityV2} => Sensor {@link HumidityV2}</li>
 * <li>Device {@link BrickIMU} => Sensor {@link IMU}</li>
 * <li>Device {@link BrickIMUV2} => Sensor {@link IMUV2}</li>
 * <li>Device {@link BrickletIO16} => Sensor {@link IO16}</li>
 * <li>Device {@link BrickletIO16V2} => Sensor {@link IO16V2}</li>
 * <li>Device {@link BrickletRGBLEDV2} => Sensor {@link LedRGBV2}</li>
 * <li>Device {@link BrickletAmbientLight} => Sensor {@link LightAmbient}</li>
 * <li>Device {@link BrickletAmbientLightV2} => Sensor {@link LightAmbientV2}</li>
 * <li>Device {@link BrickletAmbientLightV3} => Sensor {@link LightAmbientV3}</li>
 * <li>Device {@link BrickletColor} => Sensor {@link LightColor}</li>
 * <li>Device {@link BrickletUVLight} => Sensor {@link LightUv}</li>
 * <li>Device {@link BrickletUVLightV2} => Sensor {@link LightUvV2}</li>
 * <li>Device {@link DummyDevice} => Sensor {@link LocalAudio}</li>
 * <li>Device {@link DummyDevice} => Sensor {@link LocalControl}</li>
 * <li>Device {@link BrickMaster} => Sensor {@link Master}</li>
 * <li>Device {@link BrickletMotionDetector} => Sensor {@link MotionDetector}</li>
 * <li>Device {@link BrickletMotionDetectorV2} => Sensor {@link MotionDetectorV2}</li>
 * <li>Device {@link BrickletRotaryEncoderV2} => Sensor {@link RotaryV2}</li>
 * <li>Device {@link BrickServo} => Sensor {@link Servo}</li>
 * <li>Device {@link BrickletSoundIntensity} => Sensor {@link SoundIntensity}</li>
 * <li>Device {@link BrickletSoundPressureLevel} => Sensor {@link SoundPressure}</li>
 * <li>Device {@link BrickletPiezoSpeaker} => Sensor {@link Speaker}</li>
 * <li>Device {@link BrickletTemperature} => Sensor {@link Temperature}</li>
 * <li>Device {@link BrickletTemperatureV2} => Sensor {@link TemperatureV2}</li>
 * <li>Device {@link BrickletTilt} => Sensor {@link Tilt}</li>
 * </ul> */
public class SensorRegistry {
    public static final int CALLBACK_PERIOD = 64;

    private static final ConcurrentHashMap<Class<? extends Device>, Sensor.SensorFactory> sensorMap = initSensor();

    private static final ConcurrentHashMap<Integer, Sensor.DeviceFactory> deviceMap = initDevice();

    public static Sensor.SensorFactory getSensor(final Class<? extends Device> device) {
        return sensorMap.get(device);
    }

    public static Sensor.DeviceFactory getDevice(final Integer deviceIdentifier) {
        return deviceMap.get(deviceIdentifier);
    }

    public static List<Class> getDeviceAvailableDevices() {
        return new ArrayList<>(sensorMap.keySet());
    }

    private static ConcurrentHashMap<Class<? extends Device>, Sensor.SensorFactory> initSensor() {
        final ConcurrentHashMap<Class<? extends Device>, Sensor.SensorFactory> registry = new ConcurrentHashMap<>();
        registry.put(BrickletAccelerometer.class, Accelerometer::new);
        registry.put(BrickletAccelerometerV2.class, AccelerometerV2::new);
        registry.put(BrickletAirQuality.class, AirQuality::new);
        registry.put(BrickletBarometer.class, Barometer::new);
        registry.put(BrickletBarometerV2.class, BarometerV2::new);
        registry.put(BrickletRGBLEDButton.class, ButtonRGB::new);
        registry.put(BrickDC.class, DC::new);
        registry.put(DummyDevice.class, Default::new);
        registry.put(BrickletLCD128x64.class, DisplayLcd128x64::new);
        registry.put(BrickletLCD20x4.class, DisplayLcd20x4::new);
        registry.put(BrickletSegmentDisplay4x7.class, DisplaySegment::new);
        registry.put(BrickletSegmentDisplay4x7V2.class, DisplaySegmentV2::new);
        registry.put(BrickletDistanceIR.class, DistanceIR::new);
        registry.put(BrickletDistanceIRV2.class, DistanceIRV2::new);
        registry.put(BrickletDistanceUS.class, DistanceUS::new);
        registry.put(BrickletDualButtonV2.class, DualButton::new);
        registry.put(BrickletHumidity.class, Humidity::new);
        registry.put(BrickletHumidityV2.class, HumidityV2::new);
        registry.put(BrickIMU.class, IMU::new);
        registry.put(BrickIMUV2.class, IMUV2::new);
        registry.put(BrickletIO16.class, IO16::new);
        registry.put(BrickletIO16V2.class, IO16V2::new);
        registry.put(BrickletRGBLEDV2.class, LedRGBV2::new);
        registry.put(BrickletAmbientLight.class, LightAmbient::new);
        registry.put(BrickletAmbientLightV2.class, LightAmbientV2::new);
        registry.put(BrickletAmbientLightV3.class, LightAmbientV3::new);
        registry.put(BrickletColor.class, LightColor::new);
        registry.put(BrickletUVLight.class, LightUv::new);
        registry.put(BrickletUVLightV2.class, LightUvV2::new);
        registry.put(DummyDevice.class, LocalAudio::new);
        registry.put(DummyDevice.class, LocalControl::new);
        registry.put(BrickMaster.class, Master::new);
        registry.put(BrickletMotionDetector.class, MotionDetector::new);
        registry.put(BrickletMotionDetectorV2.class, MotionDetectorV2::new);
        registry.put(BrickletRotaryEncoderV2.class, RotaryV2::new);
        registry.put(BrickServo.class, Servo::new);
        registry.put(BrickletSoundIntensity.class, SoundIntensity::new);
        registry.put(BrickletSoundPressureLevel.class, SoundPressure::new);
        registry.put(BrickletPiezoSpeaker.class, Speaker::new);
        registry.put(BrickletTemperature.class, Temperature::new);
        registry.put(BrickletTemperatureV2.class, TemperatureV2::new);
        registry.put(BrickletTilt.class, Tilt::new);
        return registry;
    }

    private static ConcurrentHashMap<Integer, Sensor.DeviceFactory> initDevice() {
        final ConcurrentHashMap<Integer, Sensor.DeviceFactory> registry = new ConcurrentHashMap<>();
        registry.put(BrickletAccelerometer.DEVICE_IDENTIFIER, BrickletAccelerometer::new);
        registry.put(BrickletAccelerometerV2.DEVICE_IDENTIFIER, BrickletAccelerometerV2::new);
        registry.put(BrickletAirQuality.DEVICE_IDENTIFIER, BrickletAirQuality::new);
        registry.put(BrickletBarometer.DEVICE_IDENTIFIER, BrickletBarometer::new);
        registry.put(BrickletBarometerV2.DEVICE_IDENTIFIER, BrickletBarometerV2::new);
        registry.put(BrickletRGBLEDButton.DEVICE_IDENTIFIER, BrickletRGBLEDButton::new);
        registry.put(BrickDC.DEVICE_IDENTIFIER, BrickDC::new);
        registry.put(DummyDevice.DEVICE_IDENTIFIER, DummyDevice::new);
        registry.put(BrickletLCD128x64.DEVICE_IDENTIFIER, BrickletLCD128x64::new);
        registry.put(BrickletLCD20x4.DEVICE_IDENTIFIER, BrickletLCD20x4::new);
        registry.put(BrickletSegmentDisplay4x7.DEVICE_IDENTIFIER, BrickletSegmentDisplay4x7::new);
        registry.put(BrickletSegmentDisplay4x7V2.DEVICE_IDENTIFIER, BrickletSegmentDisplay4x7V2::new);
        registry.put(BrickletDistanceIR.DEVICE_IDENTIFIER, BrickletDistanceIR::new);
        registry.put(BrickletDistanceIRV2.DEVICE_IDENTIFIER, BrickletDistanceIRV2::new);
        registry.put(BrickletDistanceUS.DEVICE_IDENTIFIER, BrickletDistanceUS::new);
        registry.put(BrickletDualButtonV2.DEVICE_IDENTIFIER, BrickletDualButtonV2::new);
        registry.put(BrickletHumidity.DEVICE_IDENTIFIER, BrickletHumidity::new);
        registry.put(BrickletHumidityV2.DEVICE_IDENTIFIER, BrickletHumidityV2::new);
        registry.put(BrickIMU.DEVICE_IDENTIFIER, BrickIMU::new);
        registry.put(BrickIMUV2.DEVICE_IDENTIFIER, BrickIMUV2::new);
        registry.put(BrickletIO16.DEVICE_IDENTIFIER, BrickletIO16::new);
        registry.put(BrickletIO16V2.DEVICE_IDENTIFIER, BrickletIO16V2::new);
        registry.put(BrickletRGBLEDV2.DEVICE_IDENTIFIER, BrickletRGBLEDV2::new);
        registry.put(BrickletAmbientLight.DEVICE_IDENTIFIER, BrickletAmbientLight::new);
        registry.put(BrickletAmbientLightV2.DEVICE_IDENTIFIER, BrickletAmbientLightV2::new);
        registry.put(BrickletAmbientLightV3.DEVICE_IDENTIFIER, BrickletAmbientLightV3::new);
        registry.put(BrickletColor.DEVICE_IDENTIFIER, BrickletColor::new);
        registry.put(BrickletUVLight.DEVICE_IDENTIFIER, BrickletUVLight::new);
        registry.put(BrickletUVLightV2.DEVICE_IDENTIFIER, BrickletUVLightV2::new);
        registry.put(DummyDevice.DEVICE_IDENTIFIER, DummyDevice::new);
        registry.put(DummyDevice.DEVICE_IDENTIFIER, DummyDevice::new);
        registry.put(BrickMaster.DEVICE_IDENTIFIER, BrickMaster::new);
        registry.put(BrickletMotionDetector.DEVICE_IDENTIFIER, BrickletMotionDetector::new);
        registry.put(BrickletMotionDetectorV2.DEVICE_IDENTIFIER, BrickletMotionDetectorV2::new);
        registry.put(BrickletRotaryEncoderV2.DEVICE_IDENTIFIER, BrickletRotaryEncoderV2::new);
        registry.put(BrickServo.DEVICE_IDENTIFIER, BrickServo::new);
        registry.put(BrickletSoundIntensity.DEVICE_IDENTIFIER, BrickletSoundIntensity::new);
        registry.put(BrickletSoundPressureLevel.DEVICE_IDENTIFIER, BrickletSoundPressureLevel::new);
        registry.put(BrickletPiezoSpeaker.DEVICE_IDENTIFIER, BrickletPiezoSpeaker::new);
        registry.put(BrickletTemperature.DEVICE_IDENTIFIER, BrickletTemperature::new);
        registry.put(BrickletTemperatureV2.DEVICE_IDENTIFIER, BrickletTemperatureV2::new);
        registry.put(BrickletTilt.DEVICE_IDENTIFIER, BrickletTilt::new);
        return registry;
    }
}
